
# A Quick Introduction to Numerical Data Manipulation with Python and NumPy

## What is NumPy?

[NumPy](https://numpy.org/doc/stable/index.html) stands for numerical Python. It's the backbone of all kinds of scientific and numerical computing in Python.

And since machine learning is all about turning data into numbers and then figuring out the patterns, NumPy often comes into play.

<img src="../images/numpy-6-step-ml-framework-tools-numpy-highlight.png" alt="a 6 step machine learning framework along will tools you can use for each step" width="700"/>

## Why NumPy?

You can do numerical calculations using pure Python. In the beginning, you might think Python is fast but once your data gets large, you'll start to notice slow downs.

One of the main reasons you use NumPy is because it's fast. Behind the scenes, the code has been optimized to run using C. Which is another programming language, which can do things much faster than Python.

The benefit of this being behind the scenes is you don't need to know any C to take advantage of it. You can write your numerical computations in Python using NumPy and get the added speed benefits.

If your curious as to what causes this speed benefit, it's a process called vectorization. [Vectorization](https://en.wikipedia.org/wiki/Vectorization) aims to do calculations by avoiding loops as loops can create potential bottlenecks.

NumPy achieves vectorization through a process called [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting).

## What does this notebook cover?

The NumPy library is very capable. However, learning everything off by heart isn't necessary. Instead, this notebook focuses on the main concepts of NumPy and the `ndarray` datatype.

You can think of the `ndarray` datatype as a very flexible array of numbers.

More specifically, we'll look at:
* NumPy datatypes & attributes
* Creating arrays
* Viewing arrays & matrices (indexing)
* Manipulating & comparing arrays
* Sorting arrays
* Use cases (examples of turning things into numbers)

After going through it, you'll have the base knolwedge of NumPy you need to keep moving forward.

## 0. Importing NumPy

To get started using NumPy, the first step is to import it. 

The most common way (and method you should use) is to import NumPy as the abbreviation `np`.

If you see the letters `np` used anywhere in machine learning or data science, it's probably referring to the NumPy library.

In [2]:
import numpy as np

# Check the version
print(np.__version__)

2.3.1


## 1. DataTypes and attributes

> **Note:** Important to remember the main type in NumPy is `ndarray`, even seemingly different kinds of arrays are still `ndarray`'s. This means an operation you do on one array, will work on another.

In [3]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [4]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [5]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [6]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Anatomy of an array

<img src="../images/numpy-anatomy-of-an-array-updated.png" alt="anatomy of a numpy array"/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimension (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-dimensional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

### pandas DataFrame out of NumPy arrays

This is to examplify how NumPy is the backbone of many other libraries.

In [10]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), 
                                    columns=['a', 'b', 'c'])
df

a  b  c
0  7  0  9
1  7  9  6
2  3  4  9
3  7  9  7
4  5  2  2

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

* `np.array()`
* `np.ones()`
* `np.zeros()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers
* Searching the documentation example (finding `np.unique()` and using it)

In [12]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [13]:
simple_array = np.array((1, 2, 3))
simple_array, simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

In [14]:
# Create an array of ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# The default datatype is 'float64'
ones.dtype

dtype('float64')

In [16]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [17]:
# Create an array of zeros
zeros = np.zeros((5, 3, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
# Create an array within a range of values
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[2, 3, 8],
       [4, 9, 4],
       [6, 6, 6],
       [4, 0, 9],
       [3, 1, 1]], dtype=int32)

In [21]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))

array([[0.56926018, 0.62638428, 0.79171567],
       [0.05315481, 0.75824805, 0.93310491],
       [0.16282204, 0.36753114, 0.71767702],
       [0.79414509, 0.34842356, 0.92709196],
       [0.83038646, 0.51566256, 0.80159248]])

In [22]:
# Random 5x3 array of floats (between 0 & 1), similar to above
np.random.rand(5, 3)

array([[0.76223544, 0.44562122, 0.81970498],
       [0.46166459, 0.27449269, 0.65744827],
       [0.60915927, 0.37159893, 0.88669374],
       [0.78090757, 0.88822398, 0.96194099],
       [0.92401401, 0.26201456, 0.87049286]])

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

Let's see it.

In [25]:
import numpy as np

np.random.seed(1)
print(np.random.rand(3))

np.random.seed(0) # Setting the seed again to demonstrate reproducibility
print(np.random.rand(3))
np.random.seed(1)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[0.5488135  0.71518937 0.60276338]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [19]:

# Set random seed to 0
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(1, 1))

array([[5]])

In [12]:

# Set random seed to 0
np.random.seed(1)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [9]:

# Set random seed to 0
np.random.seed(2)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

With `np.random.seed()` set, every time you run the cell above, the same random numbers will be generated.

What if `np.random.seed()` wasn't set?

Every time you run the cell below, a new set of numbers will appear.

In [51]:
# Make more random numbers
np.random.randint(10, size=(5, 3))

array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]])

Let's see it in action again, we'll stay consistent and set the random seed to 0.

In [52]:
# Set random seed to same number as above
np.random.seed(0)

# The same random numbers come out
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

Because `np.random.seed()` is set to 0, the random numbers are the same as the cell with `np.random.seed()` set to 0 as well.

Setting `np.random.seed()` is not 100% necessary but it's helpful to keep numbers the same throughout your experiments.

For example, say you wanted to split your data randomly into training and test sets.

Every time you randomly split, you might get different rows in each set.

If you shared your work with someone else, they'd get different rows in each set too.

Setting `np.random.seed()` ensures there's still randomness, it just makes the randomness repeatable. Hence the 'pseudo-random' numbers.

In [54]:
import pandas as pd
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

### What unique values are in the array a3?

Now you've seen a few different ways to create arrays, as an exercise, try find out what NumPy function you could use to find the unique values are within the `a3` array.

You might want to search some like, "how to find the unqiue values in a numpy array".

In [30]:
# Your code here

## 3. Viewing arrays and matrices (indexing)

Remember, because arrays and matrices are both `ndarray`'s, they can be viewed in similar ways.

Let's check out our 3 arrays again.

In [65]:
a1

array([1, 2, 3])

In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Array shapes are always listed in the format `(row, column, n, n, n...)` where `n` is optional extra dimensions.

In [70]:
a1[2]

3

In [71]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# Get 2nd row (index 1) of a2
a2[1]
a2[1][0]

np.float64(4.0)

In [38]:
# Get the first 2 values of the first 2 rows of both arrays
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

This takes a bit of practice, especially when the dimensions get higher. Usually, it takes me a little trial and error of trying to get certain values, viewing the output in the notebook and trying again.

NumPy arrays get printed from outside to inside. This means the number at the end of the shape comes first, and the number at the start of the shape comes last.

## 4. Manipulating and comparing arrays
* Arithmetic
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * [Dot product](https://www.mathsisfun.com/algebra/matrix-multiplying.html) - `np.dot()`
    * Broadcasting
* Aggregation
    * `np.sum()` - faster than Python's `.sum()` for NumPy arrays
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - find index of minimum value
    * `np.argmax()` - find index of maximum value
    * These work on all `ndarray`'s
        * `a4.min(axis=0)` -- you can use axis as well
* Reshaping
    * `np.reshape()`
* Transposing
    * `a3.T` 
* Comparison operators
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`

### Arithmetic

In [43]:
np.random.randint(10,size=(10,2)).size

20

In [52]:
np.random.random(size=(4,5))

array([[0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232],
       [0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673]])

In [20]:
a1

array([1, 2, 3])

In [31]:
a1.ndim

1

In [36]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [28]:
a1

array([1, 2, 3])

In [37]:
ones.ndim

1

In [38]:
# Add two arrays
a1 + ones

array([2., 3., 4.])

In [45]:
# Subtract two arrays
a1 - ones

array([0., 1., 2.])

In [46]:
# Multiply two arrays
a1 * ones

array([1., 2., 3.])

In [47]:
# Multiply two arrays
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [29]:
a1.shape, a2.shape

((3,), (2, 3))

In [30]:
# This will error as the arrays have a different number of dimensions (2, 3) vs. (2, 3, 3) 
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [78]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Broadcasting

- What is broadcasting?
    - Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data. This saves time and space. For example, if you have a 3x3 array (A) and want to add a 1x3 array (B), NumPy will add the row of (B) to every row of (A).

- Rules of Broadcasting
    1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
    
    
**The broadcasting rule:**
In order to broadcast, the size of the trailing axes for both arrays in an operation must be either the same size or one of them must be one.

In [78]:
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
a =np.array(arr1)
b =np.array(arr2)
a/b

array([1.        , 9.        , 0.5       , 4.2       , 3.83333333])

In [79]:
a1

array([1, 2, 3])

In [73]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [80]:
a1.shape

(3,)

In [81]:
a2.shape

(2, 3)

In [82]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
a1 + a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [84]:
a2 + 2

array([[3. , 4. , 5.3],
       [6. , 7. , 8.5]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [86]:
# Raises an error because there's a shape mismatch (2, 3) vs. (2, 3, 3)
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [90]:
# Divide two arrays
a1 / ones

ValueError: operands could not be broadcast together with shapes (3,) (10,2) 

In [32]:
a1

array([1, 2, 3])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [88]:
# Divide using floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [91]:
# Take an array to a power
a1 ** 2

array([1, 4, 9])

In [92]:
# You can also use np.square()
np.square(a1)

array([1, 4, 9])

In [34]:
a1

array([1, 2, 3])

In [62]:
# Modulus divide (what's the remainder)
a1 % 2

array([1, 0, 1])

You can also find the log or exponential of an array using `np.log()` and `np.exp()`.

In [66]:
np.sum(a1)

np.int64(6)

NumPy's `np.sum()` is still fast but Python's `sum()` is faster on Python `list`s. 

In [54]:
import pandas as pd

In [62]:
# Find the mean
a2.mean()
# print(type(a2.mean()))

3.6333333333333333

In [60]:
np.mean(a2)
print(type(np.mean(a2)))

<class 'numpy.float64'>


In [74]:
# Find the max
np.max(a2)

np.float64(6.5)

In [75]:
# Find the min
np.min(a2)

np.float64(1.0)

In [76]:
# Find the standard deviation
np.std(a2)

np.float64(1.8226964152656422)

In [66]:
a1

array([1, 2, 3])

In [64]:
a1.mean()

2.0

In [65]:
# Find the variance
np.var(a1)

0.6666666666666666

**What's mean?**

Mean is the same as average. You can find the average of a set of numbers by adding them up and dividing them by how many there are.

**What's standard deviation?**

[Standard deviation](https://www.mathsisfun.com/data/standard-deviation.html) is a measure of how spread out numbers are.

**What's variance?**

The [variance](https://www.mathsisfun.com/data/standard-deviation.html) is the averaged squared differences of the mean.

To work it out, you:
1. Work out the mean
2. For each number, subtract the mean and square the result
3. Find the average of the squared differences

### Reshaping

In [84]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [85]:
a2.shape

(2, 3)

In [86]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [35]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [87]:
a2.reshape(2, 3, 1) + a3

array([[[ 2. ,  3. ,  4. ],
        [ 6. ,  7. ,  8. ],
        [10.3, 11.3, 12.3]],

       [[14. , 15. , 16. ],
        [18. , 19. , 20. ],
        [22.5, 23.5, 24.5]]])

### Transpose

A tranpose reverses the order of the axes. 

For example, an array with shape `(2, 3)` becomes `(3, 2)`.

In [88]:
a2.shape

(2, 3)

In [36]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [89]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [90]:
a2.transpose()

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [91]:
a2.T.shape

(3, 2)

For larger arrays, the default value of a tranpose is to swap the first and last axes.

For example, `(5, 3, 3)` -> `(3, 3, 5)`. 

In [95]:
matrix.T.shape

(3, 3, 5)

### Dot product

The main two rules for dot product to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
  
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`
 
**Note:** In NumPy, `np.dot()` and `@` can be used to acheive the same result for 1-2 dimension arrays. However, their behaviour begins to differ at arrays with 3+ dimensions.

In [66]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

mat1.shape, mat2.shape

((3, 3), (3, 2))

In [67]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [68]:
mat2

array([[4, 7],
       [6, 8],
       [8, 1]], dtype=int32)

In [72]:
np.dot(mat1, mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]], dtype=int32)

In [102]:
# Can also achieve np.dot() with "@" 
# (however, they may behave differently at 3D+ arrays)
mat1 @ mat2

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [55]:
np.random.seed(0)
mat3 = np.random.randint(10, size=(3,3))
mat4 = np.random.randint(10, size=(3,3))
mat3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [56]:
mat4

array([[4, 7, 6],
       [8, 8, 1],
       [6, 7, 7]], dtype=int32)

In [57]:
# This will fail as the inner dimensions of the matrices do not match
np.dot(mat3, mat4)

array([[ 38,  56,  51],
       [122, 140,  88],
       [ 64,  75,  37]], dtype=int32)

In [59]:
# 2-D arrays
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print(matrix_a)
print(matrix_b)
result = np.dot(matrix_a, matrix_b)
print("Dot Product of 2-D arrays:\n", result)
# Output: Dot Product of 2-D arrays:
# [[19 22]
# [43 50]]

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Dot Product of 2-D arrays:
 [[19 22]
 [43 50]]


In [106]:
mat3.T.shape

(3, 4)

In [107]:
# Dot product
np.dot(mat3.T, mat4)

array([[118,  96,  77],
       [145, 110, 137],
       [148, 137, 130]])

In [108]:
# Element-wise multiplication, also known as Hadamard product
mat3 * mat4

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]])

## 6. Use case

Turning an image into a NumPy array.

Why?

Because computers can use the numbers in the NumPy array to find patterns in the image and in turn use those patterns to figure out what's in the image.

This is what happens in modern computer vision algorithms.

Let's start with this beautiful image of a panda:

<img src="../images/numpy-panda.jpeg" alt="photo of a panda waving" width=450/>

In [3]:
from matplotlib.image import imread

panda = imread('./image.jpeg')
print(type(panda))

<class 'numpy.ndarray'>


In [4]:
panda.shape

(189, 266, 3)

In [5]:
panda

array([[[  0,  90, 148],
        [  0,  91, 149],
        [  0,  91, 149],
        ...,
        [  0, 100, 155],
        [  0, 100, 155],
        [  0, 100, 155]],

       [[  0,  91, 149],
        [  0,  91, 149],
        [  0,  92, 150],
        ...,
        [  0, 100, 155],
        [  0, 100, 155],
        [  0, 100, 155]],

       [[  0,  91, 149],
        [  0,  92, 150],
        [  0,  92, 150],
        ...,
        [  0, 100, 156],
        [  0, 100, 156],
        [  0, 100, 156]],

       ...,

       [[ 12,  15,   0],
        [ 15,  18,   0],
        [ 17,  20,   3],
        ...,
        [ 12,  15,   8],
        [  0,   2,   0],
        [  0,   2,   0]],

       [[ 19,  22,   3],
        [ 25,  28,  11],
        [ 29,  31,  17],
        ...,
        [ 27,  30,  23],
        [ 10,  13,   6],
        [ 10,  13,   6]],

       [[ 33,  36,  19],
        [ 28,  31,  14],
        [ 15,  17,   3],
        ...,
        [ 20,  23,  14],
        [  9,  12,   3],
        [  9,  12,   3]]

### Advanced Numpy
np.vstack: To stack arrays along vertical axis<BR>
np.hstack: To stack arrays along horizontal axis.<BR>
np.column_stack: To stack 1-D arrays as columns into 2-D arrays.<BR>
np.concatenate: To stack arrays along specified axis (axis is passed as argument).<BR>
Splitting:For splitting, we have these functions.<BR>
np.hsplit: Split array along horizontal axis.<BR>
np.vsplit: Split array along vertical axis.<BR>
np.array_split: Split array along specified axis.<BR>
Linear algebra in NumPy<BR>