In [ ]:
import numpy as np
a = np.array([[1,"a",3],[4,5,6]])
a.shape    # (2, 3)
a.dtype    # int64
a.nbytes   # 48 (6 elements * 8 bytes)
a.size


264

In [4]:
import numpy as np
 
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [5]:
import numpy as np
 
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [6]:
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)
 
# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)
 
# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [7]:

arr = np.array([[1, 2, 3],
                [0, 4, 5]])

print(np.all(arr, axis=0))  # column-wise
print(np.all(arr, axis=1))  # row-wise


[False  True  True]
[ True False]


In [8]:
import numpy as np

arr = np.array([0, 0, 0])
print(np.any(arr))


False


In [9]:
arr = np.array([0, 5, 0])
print(np.any(arr))


True


In [11]:
bool_arr = np.array([False, False, True])
print(np.any(bool_arr))


arr = np.array([[0, 0, 3],
                [0, 0, 0]])

print(np.any(arr, axis=0))  # column-wise
print(np.any(arr, axis=1))  # row-wise



True
[False False  True]
[ True False]


In [12]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [13]:
a1 = np.array([1, 2, 3])

print("Array:\n", a1)
print("ndim:", a1.ndim)
print("shape:", a1.shape)
print("size:", a1.size)
print("dtype:", a1.dtype)
print("itemsize:", a1.itemsize)
print("nbytes:", a1.nbytes)


Array:
 [1 2 3]
ndim: 1
shape: (3,)
size: 3
dtype: int32
itemsize: 4
nbytes: 12


In [14]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

print("\nArray:\n", a3)
print("ndim:", a3.ndim)
print("shape:", a3.shape)
print("size:", a3.size)
print("dtype:", a3.dtype)
print("itemsize:", a3.itemsize)
print("nbytes:", a3.nbytes)



Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
ndim: 3
shape: (2, 3, 3)
size: 18
dtype: int32
itemsize: 4
nbytes: 72


In [15]:
import numpy as np

# 1D array of 5 elements
arr1 = np.random.rand(5)
print(arr1)

# 2D array 2x3
arr2 = np.random.rand(2,3)
print(arr2)


[0.94213865 0.22518584 0.66551903 0.69034691 0.01851591]
[[0.40893612 0.92614256 0.69980227]
 [0.54178767 0.55612809 0.24603234]]


In [16]:
# Single random int between 0 and 9
print(np.random.randint(10))

# Array of 5 random ints between 0 and 9
print(np.random.randint(0, 10, size=5))

# 2x3 array of ints 1-20
print(np.random.randint(1, 21, size=(2,3)))


1
[0 6 4 7 1]
[[16 13 19]
 [10  9  4]]


In [17]:
arr = np.array([10, 20, 30, 40, 50])

# Pick 1 random element
print(np.random.choice(arr))

# Pick 3 elements with replacement
print(np.random.choice(arr, 3))

# Pick 3 elements without replacement
print(np.random.choice(arr, 3, replace=False))


40
[10 10 10]
[10 50 30]


In [20]:
np.random.seed(42)
print(np.random.rand(3))


[0.37454012 0.95071431 0.73199394]


In [19]:
arr = np.random.uniform(5, 10, size=(2,3))
print(arr)


[[7.99329242 5.7800932  5.7799726 ]
 [5.29041806 9.33088073 8.00557506]]


In [21]:
# Python Program illustrating
# numpy.insert()

import numpy as geek

#Working on 1D
arr = geek.arange(5)
print("1D arr : \n", arr)
print("Shape : ", arr.shape)

# value = 9
# index = 1   
# Insertion before first index
a = geek.insert(arr, 1, 9)
print("\nArray after insertion : ", a)
print("Shape : ", a.shape)


# Working on 2D array 
arr = geek.arange(12).reshape(3, 4)
print("\n\n2D arr : \n", arr)
print("Shape : ", arr.shape)

a = geek.insert(arr, 1, 9, axis = 1)
print("\nArray after insertion : \n", a)
print("Shape : ", a.shape)

1D arr : 
 [0 1 2 3 4]
Shape :  (5,)

Array after insertion :  [0 9 1 2 3 4]
Shape :  (6,)


2D arr : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape :  (3, 4)

Array after insertion : 
 [[ 0  9  1  2  3]
 [ 4  9  5  6  7]
 [ 8  9  9 10 11]]
Shape :  (3, 5)
